a = input('Digite algo: ')
print(f'O tipo primitivo deste valor é: {type(a)}')
print(f'É numérico? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
print(f'É decimal? {a.isdecimal()}')
print(f'É um dígito? {a.isdigit()}')
print(f'É minúsculo? {a.islower()}')
print(f'É maiúsculo? {a.isupper()}')
print(f'É um espaço? {a.isspace()}')
print(f'É capitalizado? {a.istitle()}')
print(f'É imprimível? {a.isprintable()}')
print(f'É identificador válido? {a.isidentifier()}')
